apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-imymwcaa
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-imymwcaa:653a1147d93fed891fd62b5cb47ec16c0624bfb4@sha256:9ea2a500199b0e45f2f61c146415cc2ee270eb4a861ae1d4122c2acf15120e25
          name: container-image
